[deps]
Attractors = "f3fd9213-ca85-4dba-9dfd-7fc91308fec7"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ChaosTools = "608a59af-f2a3-5ad4-90b4-758bdf3122a7"
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
CriticalTransitions = "251e6cd3-3112-48a5-99dd-66efcfd18334"
DelaunayTriangulation = "927a84f5-c5f4-47a5-9785-b46e178433df"
DiffEqNoiseProcess = "77a26b50-5914-5dd7-bc55-306e6241c503"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
DocumenterInterLinks = "d12716ef-a0f6-4df4-a9f1-a5a34e75c656"
DynamicalSystemsBase = "6e36e845-645a-534a-86f2-f5d4aa5a06b4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OptimalControl = "5f98b655-cc9a-415a-b60e-744165666948"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"

[compat]
Attractors = "1.31.1"
CairoMakie = "0.15.8"
ChaosTools = "3.5.2"
Contour = "0.6.3"
CriticalTransitions = "0.8"
DelaunayTriangulation = "1.6.6"
DiffEqNoiseProcess = "5.26.0"
Documenter = "^1.4.1"
DocumenterCitations = "1.4.1"
DocumenterInterLinks = "1.1.0"
DynamicalSystemsBase = "3.15.3"
ForwardDiff = "1.3.1"
Literate = "2.21.0"
NLPModelsIpopt = "0.11.1"
NLsolve = "4.5.1"
Optim = "1,2"
OptimalControl = "1.1.6"
Optimization = "5.4.0"
OptimizationOptimJL = "0.4.8"
OrdinaryDiffEq = "6.105.0"
Plots = "1.41.4"
StaticArrays = "1.9.16"
Statistics = "1.10, 1.11"
StatsBase = "0.34.10"
StochasticDiffEq = "6.90.0"
